language: python

python:
  - "2.7_with_system_site_packages"

before_install:
  - sudo apt-get update
  - sudo apt-get install python-gobject-2
  - sudo apt-get install dbus-x11
  - sudo apt-get install python-dbus
  - sudo apt-get install python-nose

script:
  - cd tests && python systemcalc_test.py -v
